# Generated by Django 5.2.5 on 2025-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20)),
                ('stock_description', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=10)),
            ],
        ),
    ]
