# Generated by Django 5.2.5 on 2025-08-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('Purchases', 'Stock In'), ('Sales', 'Stock Out'), ('Adj', 'Adjustment'), ('Opening', 'Opening Stock')], max_length=10)),
                ('supplier_customer_name', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=50)),
                ('transaction_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_manager.stocktransaction')),
            ],
        ),
    ]
