# Generated by Django 5.2.5 on 2025-08-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0002_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='transaction_type',
            field=models.CharField(choices=[('Purchases', 'Purchases'), ('Sales', 'Sales'), ('Adj', 'Adjustment'), ('Opening', 'Opening Stock')], max_length=10),
        ),
        migrations.CreateModel(
            name='StockCountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_counted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_manager.stocktransaction')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stock_manager.stockcountsession')),
            ],
        ),
    ]
