# Generated by Django 5.2.5 on 2025-08-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0003_stockcountsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Purchases'), ('OUT', 'Sales'), ('ADJ', 'Adjustment'), ('OPEN', 'Opening Stock')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
