# Generated by Django 5.2.5 on 2025-09-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0006_purchase_sale_delete_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='document_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='document_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
